language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.6.0
  - DJANGO=Django==1.6.1
  - DJANGO=https://github.com/django/django/zipball/master

matrix:
  allow_failures:
    - env: DJANGO=https://github.com/django/django/zipball/master

install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

script:
  - python setup.py test
  - python manage.py test
